In [18]:
import pandas as pd

data= pd.read_csv('C:\\Users\\user\\Desktop\\nlp\\ark-tweet-nlp-0.3.2\\sentiment-analysis\\data\\output\\extracted.2class.txt', header = None,delimiter="\t", names = ['y', 'X']
        )
X = pd.DataFrame(data.X.str.split(' ').tolist()).fillna("0")
y = data.iloc[:,0].values;

In [19]:
data

y                                                  X
0     positive  Jay Z joins Instagram nostalgic tribute Michae...
1     positive  anniv Princess Diana's death I still want beli...
2     positive  do u enjoy 2nd rate Michael Jackson bit Honest...
3     positive    may he R.I.P. Happy Birthday Michael Jackson :)
4     positive  I just may be actually done award show they ge...
5     positive  today you try destroy Sir hit tomorrow Michael...
6     positive  VIRGO DAY- We wished fellow Virgo Captain Mich...
7     positive  you may say oh it is August Liam Direction's b...
8     positive  Michael Jackson was man I remember watching Th...
9     positive  ALDUB RADIO MaAlden Monday NP I Just Can't Sto...
10    positive  #NP Michael Jackson Human Nature #BrunchInTheC...
11    positive  Happy 28th anniversary album generated #1's ju...
12    positive  Weeknd may be Michael Jackson reincarnated jus...
13    positive  Eric I heard love Michael Jackson got see him ...
14    positive  you got that website brothers mate school once...
15    positive  Very sad news Dr. Wayne Dyer passes away Ever ...
16    positive  #OnThisDay1987 CBS records shipped largest pre...
17    positive  I just texted friend be busy day tomorrow prep...
18    positive  mom I say birthday is me no you it mj michael ...
19    positive  Jay Z pays tribute Michael Jackson he joins In...
20    positive      better dancer Michael Jackson mon spill beans
21    positive  1st record best memory buying album own $ was ...
22    positive  #TodayInMusicHistory Michael Jackson earned 12...
23    positive  Last Saturday would have been 58th birthday Mu...
24    positive  Let us dream tomorrow where we can truly love ...
25    positive  s/o grade year when being michael jackson stil...
26    positive  Jay Z apparently joined Instagram Saturday pos...
27    positive  Remembering Michael Jackson Thursday September...
28    positive  Mojo just did mini-mix classic Michael Jackson...
29    positive  day September Michael Jackson was buried final...
...        ...                                                ...
2970  positive      just back doing car boot Bring sun Bob Marley
2971  positive  When I have kids morning we are going wake sun...
2972  positive                   Winding Sunday Bob Marley #vinyl
2973  positive  I used have dopest bob Marley shirt tomorrow n...
2974  positive  Monday Wisdom Bob Marley people feel rain othe...
2975  positive  Monday Afternoon Love Muse Legend himself Mr B...
2976  positive  Open eyes look Are you satisfied life living B...
2977  positive    Sun Is Shining Bob Marley is now ripping it #np
2978  positive  Bob Marley may be evidence cannabis makes you ...
2979  positive  Going beach Listen Bob Marley Kick back relax ...
2980  positive  last post talked listening Bob Marley Thursday...
2981  positive  Audio digitallioness Justin Nozuka Band- Mr Th...
2982  positive  Last chance you book Bob Marley showtime tomor...
2983  positive  googling I can only think couple Sun is shinin...
2984  positive  Representing Bob Marley own show day we hope y...
2985  positive  co-worker named printer Bob Marley he always b...
2986  positive  sun shall not smite I day moon night everythin...
2987  positive  Happiness is Sunday freshly squeezed oj hot bl...
2988  positive  Bob Marley's Stir it Birmingham gig Saturday e...
2989  positive  SATURDAY Live stream Japan Mad sounds fashion ...
2990  positive  sitting bench alone campus sun listening bob M...
2991  positive  sun shall not smite I day moon night Bob Marle...
2992  positive  today is celebrating anniversary Bob Marley's ...
2993  positive  TOMORROW NIGHT JAMROCK Hull guest Tanni Browne...
2994  positive      wake them legendary Bob Marley sun is shining
2995  positive  Sweet Sunday morning King Bob Marley #reggaemu...
2996  positive   I don't think better way start Sunday Bob Marley
2997  positive  Bob Marley fans dream will come true soon Wail...
2998  positive  Happy Monday everyone Have nice day S

In [43]:
import numpy as np
np.transpose(X)

0         1        2         3         4         5         6     \
0          Jay     anniv       do       may         I     today     VIRGO   
1            Z  Princess        u        he      just       you      DAY-   
2        joins   Diana's    enjoy    R.I.P.       may       try        We   
3    Instagram     death      2nd     Happy        be   destroy    wished   
4    nostalgic         I     rate  Birthday  actually       Sir    fellow   
5      tribute     still  Michael   Michael      done       hit     Virgo   
6      Michael      want  Jackson   Jackson     award  tomorrow   Captain   
7      Jackson   believe      bit        :)      show   Michael   Michael   
8   apparently       she   Honest         0      they   Jackson   Jackson   
9       joined        is     ques         0       get     WRITE     Happy   
10    Saturday    living    can't         0   Michael       OWN  Birthday   
11           0   private     feel         0   Jackson      DAMN      29th   
12           0    island     face         0  hologram     HOOKS       now   
13           0      away     song         0         0         0      time   
14           0    public      god         0         0         0         0   
15           0   Michael       so         0         0         0         0   
16           0   Jackson  obvious         0         0         0         0   
17           0         0     they         0         0         0         0   
18           0         0     want         0         0         0         0   
19           0         0       MJ         0         0         0         0   
20           0         0        0         0         0         0         0   
21           0         0        0         0         0         0         0   

           7         8                    9      ...          2990     2991  \
0           you   Michael                ALDUB   ...       sitting      sun   
1           may   Jackson                RADIO   ...         bench    shall   
2           say       was              MaAlden   ...         alone      not   
3            oh       man               Monday   ...        campus    smite   
4            it         I                   NP   ...           sun        I   
5            is  remember                    I   ...     listening      day   
6        August  watching                 Just   ...           bob     moon   
7          Liam  Thriller                Can't   ...        Marley    night   
8   Direction's    Smooth                 Stop   ...          this      Bob   
9      birthday  Criminal               Loving   ...            is   Marley   
10           no     music                  You   ...     wonderful  Wailers   
11         also     video              Michael   ...             0    NIGHT   
12      Michael       1st              Jackson   ...             0    SHIFT   
13      Jackson      time                 This   ...             0     Live   
14            0        it              Spanish   ...             0      NYC   
15            0       lit               French   ...             0        0   
16            0         0             versions   ...             0        0   
17            0         0  #ALDUBTheREVELATION   ...             0        0   
18            0         0                    0   ...             0        0   
19            0         0                    0   ...             0        0   
20            0         0                    0   ...             0        0   
21            0         0                    0   ...             0        0   

           2992      2993       2994                 2995    2996  \
0         today  TOMORROW       wake                Sweet       I   
1            is     NIGHT       them               Sunday   don't   
2   celebrating   JAMROCK  legendary              morning   think   
3   anniversary      Hull        Bob                 King  better   
4           Bob     guest     Marley                  Bob     way   
5     

In [29]:
import numpy as np
from sklearn.model_selection import KFold

kf = KFold(n_splits=10)
for train, test in kf.split(X):
 print("%s %s" % (train, test))

[ 300  301  302 ... 2997 2998 2999] [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 23

In [30]:
for train_index, test_index in kf.split(X):
 print("TRAIN:", train_index, "TEST:", test_index)

TRAIN: [ 300  301  302 ... 2997 2998 2999] TEST: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 2

In [41]:
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X.reindex(train_index);
    X.reindex(test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(y_train,y_test);
    print(X_train,X_test);

TRAIN: [ 300  301  302 ... 2997 2998 2999] TEST: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 2

KeyError: '[ 300  301  302 ... 2997 2998 2999] not in index'

In [32]:
y_train

array(['positive', 'positive', 'positive', ..., 'positive', 'positive',
       'positive'], dtype=object)

In [13]:
X = np.array( [["t01","t02","t03","t04","t05",'t06','t07','t08','t09','t10']
     
     ,["t11","t12","t13","t14",'t15','t16','t17','t18','t19','t20']
     
     ,["t21","t22","t23","t24",'t25','t26','t27','t28','t29','t30']
     
     ,["t31","t32","t33","t34",'t35','t36','t37','t38','t39','t40']
     
     ,["t41","t42","t43","t44",'t45','t46','t47','t48','t49','t50']
     
     ,["t51","t52","t53","t54",'t55','t56','t57','t58','t59','t60']
     
     ,["t61","t62","t63","t64",'t65','t66','t67','t68','t69','t70']
     
     ,["t71","t72","t73","t74",'t75','t76','t77','t78','t79','t80']
     
     ,["t81","t82","t83","t84",'t85','t86','t87','t88','t89','t90']
     
     ,["t91","t92","t93","t94",'t95','t96','t97','t98','t99','t100']
    ])
X

array([['t01', 't02', 't03', 't04', 't05', 't06', 't07', 't08', 't09',
        't10'],
       ['t11', 't12', 't13', 't14', 't15', 't16', 't17', 't18', 't19',
        't20'],
       ['t21', 't22', 't23', 't24', 't25', 't26', 't27', 't28', 't29',
        't30'],
       ['t31', 't32', 't33', 't34', 't35', 't36', 't37', 't38', 't39',
        't40'],
       ['t41', 't42', 't43', 't44', 't45', 't46', 't47', 't48', 't49',
        't50'],
       ['t51', 't52', 't53', 't54', 't55', 't56', 't57', 't58', 't59',
        't60'],
       ['t61', 't62', 't63', 't64', 't65', 't66', 't67', 't68', 't69',
        't70'],
       ['t71', 't72', 't73', 't74', 't75', 't76', 't77', 't78', 't79',
        't80'],
       ['t81', 't82', 't83', 't84', 't85', 't86', 't87', 't88', 't89',
        't90'],
       ['t91', 't92', 't93', 't94', 't95', 't96', 't97', 't98', 't99',
        't100']], dtype='<U4')

In [14]:
#all topic
allTopic = np.transpose(X)

In [20]:
import numpy as np
from sklearn.model_selection import KFold

kf = KFold(n_splits=10)
for train, test in kf.split(allTopic):
 print("%s %s" % (train, test))
for train_index, test_index in kf.split(allTopic):
    print("TRAIN:", train_index, "TEST:", test_index)
    allTopic_train, allTopic_test = allTopic[train_index], allTopic[test_index]
    print(allTopic_train,allTopic_test);

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]
TRAIN: [1 2 3 4 5 6 7 8 9] TEST: [0]
[['t02' 't12' 't22' 't32' 't42' 't52' 't62' 't72' 't82' 't92']
 ['t03' 't13' 't23' 't33' 't43' 't53' 't63' 't73' 't83' 't93']
 ['t04' 't14' 't24' 't34' 't44' 't54' 't64' 't74' 't84' 't94']
 ['t05' 't15' 't25' 't35' 't45' 't55' 't65' 't75' 't85' 't95']
 ['t06' 't16' 't26' 't36' 't46' 't56' 't66' 't76' 't86' 't96']
 ['t07' 't17' 't27' 't37' 't47' 't57' 't67' 't77' 't87' 't97']
 ['t08' 't18' 't28' 't38' 't48' 't58' 't68' 't78' 't88' 't98']
 ['t09' 't19' 't29' 't39' 't49' 't59' 't69' 't79' 't89' 't99']
 ['t10' 't20' 't30' 't40' 't50' 't60' 't70' 't80' 't90' 't100']] [['t01' 't11' 't21' 't31' 't41' 't51' 't61' 't71' 't81' 't91']]
TRAIN: [0 2 3 4 5 6 7 8 9] TEST: [1]
[['t01' 't11' 't21' 't31' 't41' 't51' 't61' 't71' 't8

In [16]:
#mutual exclusive
import numpy as np
from sklearn.model_selection import KFold

kf = KFold(n_splits=10)
for train, test in kf.split(X):
 print("%s %s" % (train, test))
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    print(X_train,X_test);

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]
TRAIN: [1 2 3 4 5 6 7 8 9] TEST: [0]
[['t11' 't12' 't13' 't14' 't15' 't16' 't17' 't18' 't19' 't20']
 ['t21' 't22' 't23' 't24' 't25' 't26' 't27' 't28' 't29' 't30']
 ['t31' 't32' 't33' 't34' 't35' 't36' 't37' 't38' 't39' 't40']
 ['t41' 't42' 't43' 't44' 't45' 't46' 't47' 't48' 't49' 't50']
 ['t51' 't52' 't53' 't54' 't55' 't56' 't57' 't58' 't59' 't60']
 ['t61' 't62' 't63' 't64' 't65' 't66' 't67' 't68' 't69' 't70']
 ['t71' 't72' 't73' 't74' 't75' 't76' 't77' 't78' 't79' 't80']
 ['t81' 't82' 't83' 't84' 't85' 't86' 't87' 't88' 't89' 't90']
 ['t91' 't92' 't93' 't94' 't95' 't96' 't97' 't98' 't99' 't100']] [['t01' 't02' 't03' 't04' 't05' 't06' 't07' 't08' 't09' 't10']]
TRAIN: [0 2 3 4 5 6 7 8 9] TEST: [1]
[['t01' 't02' 't03' 't04' 't05' 't06' 't07' 't08' 't0